USE [SW_COUNTYPERMITS]
GO

/****** Object:  Table [dbo].[SW_PERMIT_TYPE]    Script Date: 02/12/2025 11:35:08 a. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SW_PERMIT_TYPE](
	[TYPE_ID] [int] IDENTITY(1,1) NOT NULL,
	[TYPE] [varchar](50) NOT NULL,
	[DESCRIPTION] [varbinary](200) NULL,
 CONSTRAINT [PK_SW_PERMIT_TYPE] PRIMARY KEY CLUSTERED 
(
	[TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


