USE [SW_COUNTYPERMITS]
GO

/****** Object:  Table [dbo].[SW_PERMITS]    Script Date: 02/12/2025 11:35:37 a. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SW_PERMITS](
	[PERMIT_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NOT NULL,
	[TYPE_ID] [int] NOT NULL,
	[COUNTY_ID] [int] NOT NULL,
	[APPLICATION_DATE] [datetime] NULL,
 CONSTRAINT [PK_SW_PERMITS] PRIMARY KEY CLUSTERED 
(
	[PERMIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SW_PERMITS]  WITH CHECK ADD  CONSTRAINT [FK_SW_PERMITS_SW_COUNTIES] FOREIGN KEY([COUNTY_ID])
REFERENCES [dbo].[SW_COUNTIES] ([COUNTY_ID])
GO

ALTER TABLE [dbo].[SW_PERMITS] CHECK CONSTRAINT [FK_SW_PERMITS_SW_COUNTIES]
GO

ALTER TABLE [dbo].[SW_PERMITS]  WITH CHECK ADD  CONSTRAINT [FK_SW_PERMITS_SW_PERMIT_TYPE] FOREIGN KEY([TYPE_ID])
REFERENCES [dbo].[SW_PERMIT_TYPE] ([TYPE_ID])
GO

ALTER TABLE [dbo].[SW_PERMITS] CHECK CONSTRAINT [FK_SW_PERMITS_SW_PERMIT_TYPE]
GO

ALTER TABLE [dbo].[SW_PERMITS]  WITH CHECK ADD  CONSTRAINT [FK_SW_PERMITS_SW_SUBMITTERS] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[SW_SUBMITTERS] ([USER_ID])
GO

ALTER TABLE [dbo].[SW_PERMITS] CHECK CONSTRAINT [FK_SW_PERMITS_SW_SUBMITTERS]
GO


