USE [SW_COUNTYPERMITS]
GO

/****** Object:  Table [dbo].[SW_SUBMITTERS]    Script Date: 02/12/2025 11:36:05 a. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SW_SUBMITTERS](
	[USER_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
	[LASTNAME] [varchar](50) NOT NULL,
	[ADDRESS] [varchar](200) NULL,
 CONSTRAINT [PK_SW_SUBMITTERS] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


