USE [SW_COUNTYPERMITS]
GO

/****** Object:  Table [dbo].[SW_COUNTIES]    Script Date: 02/12/2025 11:25:24 a. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SW_COUNTIES](
	[COUNTY_ID] [int] IDENTITY(1,1) NOT NULL,
	[COUNTY_NAME] [varchar](100) NOT NULL,
 CONSTRAINT [PK_SW_COUNTIES] PRIMARY KEY CLUSTERED 
(
	[COUNTY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


