SELECT SWP.PERMIT_ID, SWS.NAME, SWS.LASTNAME, PT.TYPE, CO.COUNTY_NAME, SWS.ADDRESS
FROM [SW_COUNTYPERMITS].[dbo].[SW_PERMITS] SWP
JOIN [SW_COUNTYPERMITS].[dbo].[SW_SUBMITTERS] SWS ON SWP.USER_ID = SWS.USER_ID
JOIN [SW_COUNTYPERMITS].[dbo].[SW_PERMIT_TYPE] PT ON SWP.TYPE_ID = PT.TYPE_ID
JOIN [SW_COUNTYPERMITS].[dbo].[SW_COUNTIES] CO ON SWP.COUNTY_ID = CO.COUNTY_ID

SELECT TOP (1000) [PERMIT_ID]
    ,[USER_ID]
    ,[TYPE_ID]
    ,[COUNTY_ID]
    ,[APPLICATION_DATE]
FROM [SW_COUNTYPERMITS].[dbo].[SW_PERMITS]

SELECT TOP (1000) [USER_ID]
    ,[NAME]
    ,[LASTNAME]
    ,[ADDRESS]
FROM [SW_COUNTYPERMITS].[dbo].[SW_SUBMITTERS]


  